"""create leagues table

Revision ID: 5277e84c08d8
Revises: 
Create Date: 2024-03-12 16:25:28.041808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5277e84c08d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=128), nullable=False),
    sa.Column('date_of_foundation', sa.Date(), nullable=True),
    sa.Column('number_of_teams', sa.Integer(), nullable=True),
    sa.Column('level_on_pyramid', sa.Integer(), nullable=True),
    sa.Column('current_champion', sa.String(length=128), nullable=True),
    sa.Column('most_champions', sa.String(length=128), nullable=True),
    sa.Column('most_appearances', sa.String(length=128), nullable=True),
    sa.Column('top_scorer', sa.String(length=128), nullable=True),
    sa.Column('logo', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leagues')
    # ### end Alembic commands ###
